import { useEffect, useState } from "react";

type Candidate = {
  id: number;
  candidate_name?: string;
  resume_filename?: string;
  fit_score: number;
  status: string;
  bookmarked: boolean;
  created_at: string;
  recommendation?: string;
  notes?: string;
};

type SavedSearch = {
  id: string;
  name: string;
  query: string;
  created_at: string;
};

type Props = {
  candidates: Candidate[];
};

export default function RecruiterEnterpriseTools({
  candidates,
}: Props) {
  const [savedSearchName, setSavedSearchName] = useState("");
  const [savedSearchQuery, setSavedSearchQuery] = useState("");
  const [savedSearches, setSavedSearches] = useState<SavedSearch[]>([]);
  const [selectedReportCandidateId, setSelectedReportCandidateId] =
    useState<number | null>(candidates[0]?.id || null);

  useEffect(() => {
    const stored = localStorage.getItem("recruitflow_saved_searches");

    if (stored) {
      setSavedSearches(JSON.parse(stored));
    }
  }, []);

  function saveSearch() {
    if (!savedSearchName.trim() || !savedSearchQuery.trim()) {
      alert("Add a search name and query.");
      return;
    }

    const newSearch: SavedSearch = {
      id: crypto.randomUUID(),
      name: savedSearchName,
      query: savedSearchQuery,
      created_at: new Date().toISOString(),
    };

    const updated = [newSearch, ...savedSearches];

    setSavedSearches(updated);
    localStorage.setItem(
      "recruitflow_saved_searches",
      JSON.stringify(updated)
    );

    setSavedSearchName("");
    setSavedSearchQuery("");
  }

  function deleteSavedSearch(id: string) {
    const updated = savedSearches.filter((search) => search.id !== id);

    setSavedSearches(updated);
    localStorage.setItem(
      "recruitflow_saved_searches",
      JSON.stringify(updated)
    );
  }

  const selectedCandidate =
    candidates.find((candidate) => candidate.id === selectedReportCandidateId) ||
    candidates[0];

  function copyReportLink() {
    if (!selectedCandidate) return;

    const reportText = `
RecruitFlow AI Elite Candidate Report

Candidate: ${selectedCandidate.candidate_name || "Unknown Candidate"}
Resume: ${selectedCandidate.resume_filename || "N/A"}
Fit Score: ${selectedCandidate.fit_score}%
Status: ${selectedCandidate.status}
Bookmarked: ${selectedCandidate.bookmarked ? "Yes" : "No"}

Recommendation:
${selectedCandidate.recommendation || "No recommendation available."}

Generated by RecruitFlow AI Elite.
`;

    navigator.clipboard.writeText(reportText);
    alert("Recruiter report copied to clipboard.");
  }

  function printReport() {
    window.print();
  }

  return (
    <div className="space-y-10">
      <div className="rounded-3xl border border-fuchsia-400/20 bg-fuchsia-500/10 p-6">
        <p className="text-sm uppercase tracking-[0.3em] text-fuchsia-300">
          Saved Recruiter Searches
        </p>

        <h3 className="mt-2 text-2xl font-bold text-white">
          Save and Reuse Talent Searches
        </h3>

        <p className="mt-2 text-slate-300">
          Store common recruiter searches like Python FastAPI, AI Engineer, or
          React ML candidates.
        </p>

        <div className="mt-5 grid gap-4 md:grid-cols-3">
          <input
            value={savedSearchName}
            onChange={(e) => setSavedSearchName(e.target.value)}
            placeholder="Search name"
            className="rounded-2xl border border-white/10 bg-black/40 px-4 py-3 text-white outline-none"
          />

          <input
            value={savedSearchQuery}
            onChange={(e) => setSavedSearchQuery(e.target.value)}
            placeholder="Search query"
            className="rounded-2xl border border-white/10 bg-black/40 px-4 py-3 text-white outline-none"
          />

          <button
            type="button"
            onClick={saveSearch}
            className="rounded-2xl bg-fuchsia-400 px-5 py-3 font-bold text-black transition hover:bg-fuchsia-300"
          >
            Save Search
          </button>
        </div>

        {savedSearches.length > 0 ? (
          <div className="mt-6 grid gap-4 md:grid-cols-2">
            {savedSearches.map((search) => (
              <div
                key={search.id}
                className="rounded-2xl border border-white/10 bg-black/20 p-5"
              >
                <div className="text-lg font-bold text-white">
                  {search.name}
                </div>

                <div className="mt-2 text-sm text-slate-300">
                  {search.query}
                </div>

                <div className="mt-2 text-xs text-slate-500">
                  Saved {new Date(search.created_at).toLocaleString()}
                </div>

                <div className="mt-4 flex gap-3">
                  <button
                    type="button"
                    onClick={() => {
                      navigator.clipboard.writeText(search.query);
                      alert("Search query copied.");
                    }}
                    className="rounded-xl bg-white/10 px-4 py-2 text-sm text-white"
                  >
                    Copy Query
                  </button>

                  <button
                    type="button"
                    onClick={() => deleteSavedSearch(search.id)}
                    className="rounded-xl bg-rose-500/20 px-4 py-2 text-sm text-rose-200"
                  >
                    Delete
                  </button>
                </div>
              </div>
            ))}
          </div>
        ) : null}
      </div>

      <div className="rounded-3xl border border-amber-400/20 bg-amber-500/10 p-6">
        <p className="text-sm uppercase tracking-[0.3em] text-amber-300">
          Shareable Recruiter Reports
        </p>

        <h3 className="mt-2 text-2xl font-bold text-white">
          Generate Candidate Hiring Reports
        </h3>

        <p className="mt-2 text-slate-300">
          Create a recruiter-ready summary that can be copied, shared, or
          printed as a hiring report.
        </p>

        <div className="mt-5">
          <select
            value={selectedReportCandidateId || ""}
            onChange={(e) => setSelectedReportCandidateId(Number(e.target.value))}
            className="w-full rounded-2xl border border-white/10 bg-black/40 px-4 py-3 text-white outline-none"
          >
            {candidates.map((candidate) => (
              <option key={candidate.id} value={candidate.id}>
                {candidate.candidate_name || "Unknown Candidate"} —{" "}
                {candidate.fit_score}%
              </option>
            ))}
          </select>
        </div>

        {selectedCandidate ? (
          <div className="mt-6 rounded-2xl border border-white/10 bg-black/30 p-6">
            <div className="text-sm uppercase tracking-[0.25em] text-amber-300">
              Recruiter Report
            </div>

            <h4 className="mt-3 text-2xl font-bold text-white">
              {selectedCandidate.candidate_name || "Unknown Candidate"}
            </h4>

            <div className="mt-1 text-sm text-slate-400">
              {selectedCandidate.resume_filename}
            </div>

            <div className="mt-5 grid gap-4 md:grid-cols-3">
              <div className="rounded-xl bg-white/5 p-4">
                <div className="text-sm text-slate-400">Fit Score</div>
                <div className="text-3xl font-black text-amber-300">
                  {selectedCandidate.fit_score}%
                </div>
              </div>

              <div className="rounded-xl bg-white/5 p-4">
                <div className="text-sm text-slate-400">Status</div>
                <div className="text-xl font-bold capitalize text-white">
                  {selectedCandidate.status}
                </div>
              </div>

              <div className="rounded-xl bg-white/5 p-4">
                <div className="text-sm text-slate-400">Bookmarked</div>
                <div className="text-xl font-bold text-white">
                  {selectedCandidate.bookmarked ? "Yes" : "No"}
                </div>
              </div>
            </div>

            <div className="mt-5 text-slate-300">
              <strong className="text-white">Recommendation:</strong>{" "}
              {selectedCandidate.recommendation ||
                "No recommendation available."}
            </div>

            <div className="mt-6 flex flex-wrap gap-3">
              <button
                type="button"
                onClick={copyReportLink}
                className="rounded-2xl bg-amber-400 px-5 py-3 font-bold text-black"
              >
                Copy Report
              </button>

              <button
                type="button"
                onClick={printReport}
                className="rounded-2xl border border-white/10 bg-black/30 px-5 py-3 font-bold text-white"
              >
                Print / Save PDF
              </button>
            </div>
          </div>
        ) : null}
      </div>
    </div>
  );
}